<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8c0a8a24-14a1-45c3-b67b-beade5825185</testSuiteGuid>
   <testCaseLink>
      <guid>69e16139-3e41-458d-b8d3-5458690ccff7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'wrongformated'</defaultValue>
         <description></description>
         <id>cb348728-b7c7-4808-8ffc-fa1888fa3bdd</id>
         <masked>false</masked>
         <name>email</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Forgot password but email badly formated</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b67d1bb8-468b-4d45-976c-67da034b40c9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data 2</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b67d1bb8-468b-4d45-976c-67da034b40c9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>cb348728-b7c7-4808-8ffc-fa1888fa3bdd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
